import { expect, test } from "bun:test";
import { readFileSync } from "node:fs";

import {
  createMsgWranglerConfig,
  normalizeGeneratedTypes,
  validateMsgD1DatabaseId,
} from "./wrangler-config";
import {
  buildMsgMiniflareRateLimits,
  buildMsgWranglerRateLimits,
  parseMsgRateLimitPolicyJson,
  validateMsgRateLimitPolicy,
} from "./msg-rate-limit-policy";
import { fileURLToPath } from "node:url";
import { resolveMsgWranglerArguments } from "./wrangler-config";

test("creates a production config only from a validated D1 database id", () => {
  const config = createMsgWranglerConfig("11111111-2222-4333-8444-555555555555");

  expect(config).toContain('"database_id": "11111111-2222-4333-8444-555555555555"');
  expect(config).toContain('"pattern": "msg.0000.chat"');
  expect(config).toContain("worker/src/worker-entry.ts");
  expect(config).toContain("worker/migrations");
  expect(config).toContain("worker/public");
  expect(config).not.toContain("__MSG_D1_DATABASE_ID__");
});

test("uses a compatibility date that Cloudflare accepts on the current UTC day", () => {
  const config = JSON.parse(createMsgWranglerConfig("11111111-2222-4333-8444-555555555555")) as {
    compatibility_date: string;
  };
  const currentUtcDate = new Date().toISOString().slice(0, 10);

  expect(config.compatibility_date <= currentUtcDate).toBe(true);
});

test("configures separate one-minute production rate-limit bindings", () => {
  const config = JSON.parse(createMsgWranglerConfig("11111111-2222-4333-8444-555555555555")) as {
    ratelimits?: readonly { name: string; namespace_id: string; simple: { limit: number; period: number } }[];
  };

  expect(config.ratelimits).toEqual([
    { name: "MSG_RATE_LIMIT_CREATION", namespace_id: "2026080901", simple: { limit: 6, period: 60 } },
    { name: "MSG_RATE_LIMIT_READS", namespace_id: "2026080902", simple: { limit: 60, period: 60 } },
    { name: "MSG_RATE_LIMIT_POSTS", namespace_id: "2026080903", simple: { limit: 20, period: 60 } },
    { name: "MSG_RATE_LIMIT_LIVE", namespace_id: "2026080904", simple: { limit: 10, period: 60 } },
  ]);
});

test("feeds managed and self-host examples through the shared binding builders", () => {
  for (const [fileName, expectedPosts] of [["managed", 20], ["self-host", 40]] as const) {
    const policy = parseMsgRateLimitPolicyJson(readFileSync(new URL(`../docs/examples/msg-rate-limit-policy.${fileName}.json`, import.meta.url), "utf8"));
    const wranglerBindings = buildMsgWranglerRateLimits(policy);
    const runtimeBindings = buildMsgMiniflareRateLimits(policy);
    expect(wranglerBindings.find((binding) => binding.name === "MSG_RATE_LIMIT_POSTS")?.simple.limit).toBe(expectedPosts);
    expect(runtimeBindings.MSG_RATE_LIMIT_POSTS.simple.limit).toBe(expectedPosts);
    expect(JSON.parse(createMsgWranglerConfig("11111111-2222-4333-8444-555555555555", policy)).ratelimits).toEqual(wranglerBindings);
  }
});

test("rejects incomplete, unknown, contradictory, and malformed policy values", () => {
  const valid = {
    creation: { limit: 1, namespace_id: "1" },
    reads: { limit: 2, namespace_id: "2" },
    posts: { limit: 3, namespace_id: "3" },
    live: { limit: 4, namespace_id: "4" },
  };
  expect(validateMsgRateLimitPolicy(valid)).toEqual(valid);
  expect(() => validateMsgRateLimitPolicy({ ...valid, live: undefined })).toThrow("live");
  expect(() => validateMsgRateLimitPolicy({ ...valid, extra: { limit: 1, namespace_id: "5" } })).toThrow("unknown");
  expect(() => validateMsgRateLimitPolicy({ ...valid, posts: { limit: 1.5, namespace_id: "5" } })).toThrow("positive integer");
  expect(() => validateMsgRateLimitPolicy({ ...valid, live: { limit: 4, namespace_id: "3" } })).toThrow("distinct");
  expect(() => validateMsgRateLimitPolicy({ ...valid, live: { limit: 4, namespace_id: "4", period: 10 } })).toThrow("60");
  expect(() => parseMsgRateLimitPolicyJson("{ malformed")).toThrow("valid JSON");
});

test("rejects placeholders and malformed D1 database ids", () => {
  for (const value of ["", "__MSG_D1_DATABASE_ID__", "not-a-database-id", "11111111-2222-4333-8444-55555555555z"]) {
    expect(() => validateMsgD1DatabaseId(value)).toThrow("MSG_D1_DATABASE_ID");
  }
});

test("normalizes only generated Wrangler provenance and trailing whitespace", () => {
  const generatedConfig = "/tmp/0000-msg-wrangler-random/wrangler.msg.jsonc";
  const source = [
    "/* eslint-disable */",
    `// Generated by Wrangler by running \`wrangler types --config=${generatedConfig} worker/worker-configuration.d.ts\` (hash: stable)`,
    "interface Env { ",
    "\tvalue: string;\t",
    "}",
    "",
  ].join("\n");

  expect(normalizeGeneratedTypes(source, generatedConfig)).toBe(
    [
      "/* eslint-disable */",
      "// Generated by Wrangler by running `wrangler types --config=wrangler.msg.jsonc worker/worker-configuration.d.ts` (hash: stable)",
      "interface Env {",
      "\tvalue: string;",
      "}",
      "",
    ].join("\n"),
  );
});

test("resolves Wrangler type output relative to the service despite the monorepo command cwd", () => {
  const target = fileURLToPath(new URL("../worker/worker-configuration.d.ts", import.meta.url));
  expect(resolveMsgWranglerArguments(["types", "worker/worker-configuration.d.ts", "--include-runtime=true"])).toEqual([
    "types",
    target,
    "--include-runtime=true",
  ]);
  expect(resolveMsgWranglerArguments(["deploy", "--dry-run"])).toEqual(["deploy", "--dry-run"]);
});
