/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false src/worker-configuration.d.ts` (hash: 39af99c9e671879aef84cf4fc559fe1e)
interface __BaseEnv_Env {
  DATABASES: DurableObjectNamespace<import("./worker").DatabaseObject>;
  REGISTRY: DurableObjectNamespace<import("./worker").DatabaseRegistry>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./worker");
    durableNamespaces: "DatabaseObject" | "DatabaseRegistry";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
