import { readFileSync } from "node:fs";
import { expect, test } from "bun:test";
import {
  buildPlatformMiniflareRateLimits,
  buildPlatformWranglerRateLimits,
  parsePlatformRateLimitPolicyJson,
} from "../src/rate-limit-policy";
import {
  createPlatformWranglerConfig,
  normalizeGeneratedTypes,
} from "./wrangler-config";

const customPolicy = parsePlatformRateLimitPolicyJson(
  JSON.stringify({
    login: { limit: 7, namespace_id: "301" },
    issuance: { limit: 8, namespace_id: "302" },
    management: { limit: 9, namespace_id: "303" },
    verification: { limit: 10, namespace_id: "304" },
    guestControl: { limit: 11, namespace_id: "305" },
  }),
);

test("emits native binding configuration from the validated policy", () => {
  const config = JSON.parse(createPlatformWranglerConfig(customPolicy)) as {
    ratelimits: unknown;
    vars: { PLATFORM_RATE_LIMIT_POLICY: string };
  };
  expect(config.ratelimits).toEqual(
    buildPlatformWranglerRateLimits(customPolicy),
  );
  expect(config.vars.PLATFORM_RATE_LIMIT_POLICY).toBe(
    JSON.stringify(customPolicy),
  );
  expect(
    buildPlatformMiniflareRateLimits(customPolicy).PLATFORM_RATE_LIMIT_LOGIN
      ?.simple.limit,
  ).toBe(7);
});

test("rejects malformed policy before Wrangler is started", () => {
  expect(() =>
    createPlatformWranglerConfig({
      ...customPolicy,
      guestControl: { limit: 11, namespace_id: "304" },
    }),
  ).toThrow("distinct");
});

test("normalizes generated Wrangler provenance without changing source content", () => {
  const generatedConfig =
    "/tmp/0000-platform-wrangler-random/wrangler.platform.jsonc";
  const source = [
    "/* eslint-disable */",
    `// Generated by Wrangler by running \`wrangler types --config=${generatedConfig} worker-configuration.d.ts\` (hash: stable)`,
    "interface Env { ",
    "\tvalue: string;\t",
    "}",
    "",
  ].join("\n");
  expect(normalizeGeneratedTypes(source, generatedConfig)).toBe(
    [
      "/* eslint-disable */",
      "// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc worker-configuration.d.ts` (hash: stable)",
      "interface Env {",
      "\tvalue: string;",
      "}",
      "",
    ].join("\n"),
  );
  expect(
    readFileSync(new URL("../wrangler.jsonc", import.meta.url), "utf8"),
  ).toContain('"PLATFORM_RATE_LIMIT_POLICY": ""');
});
