import { readFileSync, rmSync, writeFileSync } from "node:fs";
import { randomUUID } from "node:crypto";
import { dirname, isAbsolute, join, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import {
  buildPlatformWranglerRateLimits,
  DEFAULT_PLATFORM_RATE_LIMIT_POLICY,
  parsePlatformRateLimitPolicyJson,
  validatePlatformRateLimitPolicy,
  type PlatformRateLimitPolicy,
} from "../src/rate-limit-policy";

const serviceRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const monorepoRoot = join(serviceRoot, "../..");
const configPath = join(serviceRoot, "wrangler.jsonc");
const rateLimitSectionPattern = /"ratelimits": \[[\s\S]*?\n  \],\n  "vars":/u;
const policyVarPattern = /("PLATFORM_RATE_LIMIT_POLICY": )"[^"]*"/u;

function loadRateLimitPolicy(): PlatformRateLimitPolicy {
  const policyFile = process.env.PLATFORM_RATE_LIMIT_POLICY_FILE;
  const inlinePolicy = process.env.PLATFORM_RATE_LIMIT_POLICY;
  if (policyFile !== undefined && inlinePolicy?.trim()) {
    throw new Error(
      "Set only one of PLATFORM_RATE_LIMIT_POLICY_FILE or PLATFORM_RATE_LIMIT_POLICY.",
    );
  }
  if (policyFile !== undefined) {
    if (policyFile.trim() === "") {
      throw new Error(
        "PLATFORM_RATE_LIMIT_POLICY_FILE must name a JSON policy file.",
      );
    }
    const path = isAbsolute(policyFile)
      ? policyFile
      : resolve(serviceRoot, policyFile);
    return parsePlatformRateLimitPolicyJson(readFileSync(path, "utf8"));
  }
  if (inlinePolicy !== undefined && inlinePolicy !== "") {
    return parsePlatformRateLimitPolicyJson(inlinePolicy);
  }
  return DEFAULT_PLATFORM_RATE_LIMIT_POLICY;
}

export function createPlatformWranglerConfig(
  policy: unknown = DEFAULT_PLATFORM_RATE_LIMIT_POLICY,
): string {
  const template = readFileSync(configPath, "utf8");
  const validated = validatePlatformRateLimitPolicy(policy);
  const withRateLimits = template.replace(
    rateLimitSectionPattern,
    `"ratelimits": ${JSON.stringify(buildPlatformWranglerRateLimits(validated), null, 2)},\n  "vars":`,
  );
  if (withRateLimits === template) {
    throw new Error(
      "The Platform Wrangler config template is missing its rate-limit section.",
    );
  }
  const runtimePolicy = JSON.stringify(validated);
  const withPolicy = withRateLimits.replace(
    policyVarPattern,
    `$1${JSON.stringify(runtimePolicy)}`,
  );
  if (withPolicy === withRateLimits) {
    throw new Error(
      "The Platform Wrangler config template is missing its policy variable.",
    );
  }
  return withPolicy
    .replace(
      '"$schema": "node_modules/wrangler/config-schema.json"',
      `"$schema": ${JSON.stringify(join(monorepoRoot, "node_modules/wrangler/config-schema.json"))}`,
    )
    .replace(
      '"main": "src/worker.ts"',
      `"main": ${JSON.stringify(join(serviceRoot, "src/worker.ts"))}`,
    )
    .replace(
      '"migrations_dir": "migrations"',
      `"migrations_dir": ${JSON.stringify(join(serviceRoot, "migrations"))}`,
    );
}

export function normalizeGeneratedTypes(
  contents: string,
  generatedConfig: string,
  generatedOutput?: string,
): string {
  const lines = contents.split("\n");
  const provenanceIndex = lines.findIndex((line) =>
    line.startsWith("// Generated by Wrangler by running "),
  );
  if (provenanceIndex !== -1) {
    lines[provenanceIndex] = lines[provenanceIndex].replaceAll(
      generatedConfig,
      "wrangler.jsonc",
    );
    if (generatedOutput) {
      lines[provenanceIndex] = lines[provenanceIndex].replaceAll(
        generatedOutput,
        "worker-configuration.d.ts",
      );
    }
  }
  return lines.join("\n").replace(/[ \t]+(?=\r?$)/gmu, "");
}

function typesOutputPath(args: readonly string[]): string | null {
  if (args[0] !== "types") return null;
  const output = args[1];
  if (!output || output.startsWith("-")) return null;
  return resolve(serviceRoot, output);
}

function commandArguments(args: readonly string[]): readonly string[] {
  const outputPath = typesOutputPath(args);
  if (!outputPath) return args;
  return [args[0]!, outputPath, ...args.slice(2)];
}

function main(args: readonly string[]): void {
  // Wrangler resolves project-local files and default local persistence from
  // the generated config's directory. Keep only the policy-specific config
  // temporary while placing it beside the service-owned wrangler.jsonc so
  // .dev.vars and .wrangler/state remain the normal Platform roots.
  const generatedConfig = join(
    serviceRoot,
    `.wrangler.platform.${process.pid}.${randomUUID()}.jsonc`,
  );
  try {
    writeFileSync(
      generatedConfig,
      createPlatformWranglerConfig(loadRateLimitPolicy()),
      {
        mode: 0o600,
      },
    );
    const result = spawnSync(
      "bunx",
      ["wrangler", ...commandArguments(args), "--config", generatedConfig],
      { cwd: serviceRoot, stdio: "inherit" },
    );
    if (result.error) throw result.error;
    if (result.status !== 0) {
      process.exitCode = result.status ?? 1;
      return;
    }
    const outputPath = typesOutputPath(args);
    if (outputPath) {
      writeFileSync(
        outputPath,
        normalizeGeneratedTypes(
          readFileSync(outputPath, "utf8"),
          generatedConfig,
          outputPath,
        ),
      );
    }
  } finally {
    rmSync(generatedConfig, { force: true });
  }
}

if (import.meta.main) {
  try {
    main(process.argv.slice(2));
  } catch (error) {
    process.stderr.write(
      `${error instanceof Error ? error.message : "Platform Wrangler configuration failed."}\n`,
    );
    process.exitCode = 1;
  }
}
